import type { Category } from './types';

// Seed data from CLAUDE.md. Only used on first launch and by "Restore default dishes".
export const DEFAULT_DISHES: { name: string; categories: Category[] }[] = [
  { name: 'Schnitzel', categories: ['pork'] },
  { name: 'Rouladen', categories: ['beef'] },
  { name: 'Gulasch', categories: ['beef', 'pork'] },
  { name: 'Frikadellen mit Kartoffelsalat', categories: ['beef', 'pork'] },
  { name: 'Currywurst mit Pommes', categories: ['pork'] },
  { name: 'Sauerbraten', categories: ['beef'] },
  { name: 'Königsberger Klopse', categories: ['beef', 'pork'] },
  { name: 'Chili con Carne', categories: ['beef', 'vegetarian'] },
  { name: 'Spaghetti Bolognese', categories: ['beef', 'vegetarian'] },
  { name: 'Lasagne', categories: ['beef', 'vegetarian'] },
  { name: 'Burger', categories: ['beef', 'chicken', 'vegetarian'] },
  { name: 'Tacos', categories: ['beef', 'chicken', 'vegetarian'] },
  { name: 'Pulled Pork Sandwich', categories: ['pork'] },
  { name: 'Pork Stir-Fry with Rice', categories: ['pork'] },
  { name: 'Hähnchen-Curry', categories: ['chicken', 'vegetarian'] },
  { name: 'Chicken Fajitas', categories: ['chicken'] },
  { name: 'Chicken Teriyaki with Rice', categories: ['chicken'] },
  { name: 'Roast Chicken with Vegetables', categories: ['chicken'] },
  { name: 'Chicken Caesar Salad', categories: ['chicken'] },
  { name: 'Paella', categories: ['chicken', 'fish'] },
  { name: 'Fish and Chips', categories: ['fish'] },
  { name: 'Lachs mit Ofengemüse', categories: ['fish'] },
  { name: 'Fischstäbchen mit Kartoffelpüree', categories: ['fish'] },
  { name: 'Shrimp Pasta', categories: ['fish'] },
  { name: 'Tuna Pasta Bake', categories: ['fish'] },
  { name: 'Fried Rice', categories: ['chicken', 'pork', 'fish', 'vegetarian'] },
  { name: 'Käsespätzle', categories: ['vegetarian'] },
  { name: 'Pfannkuchen', categories: ['vegetarian'] },
  { name: 'Gemüse-Risotto', categories: ['vegetarian'] },
  { name: 'Shakshuka', categories: ['vegetarian'] },
  { name: 'Pasta Pesto', categories: ['vegetarian'] },
  { name: 'Linsensuppe', categories: ['vegetarian', 'pork'] },
  { name: 'Vegetable Stir-Fry with Noodles', categories: ['vegetarian', 'chicken'] },
  { name: 'Pizza', categories: ['vegetarian', 'pork'] },
  { name: 'Omelette with Salad', categories: ['vegetarian'] },
];
